apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  labels:
    app: todo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: todo-frontend
          image: 543816070942.dkr.ecr.us-east-1.amazonaws.com/shubham_argocd_todo_react:4e61638229fe507d0c5228e473c1429fed4bac4c
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: /api/todos

